modular_home_robot:
# ------------ Publish all joint states ------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000
    default : true

# ------------ arm controller config ------------

## -- Position Controllers --
  joint0_position_controller:
    type: velocity_controllers/JointPositionController
    joint: joint0
    pid: {p: 1000.0, i: 0.01, d: 0.0}

  joint1_position_controller:
    type: velocity_controllers/JointPositionController
    joint: joint1
    pid: {p: 1000.0, i: 0.01, d: 0.0}

  joint2_position_controller:
    type: velocity_controllers/JointPositionController
    joint: joint2
    pid: {p: 1000.0, i: 0.01, d: 0.0}

  joint3_position_controller:
    type: velocity_controllers/JointPositionController
    joint: joint3
    pid: {p: 1000.0, i: 0.01, d: 0.0}

  joint4_position_controller:
    type: velocity_controllers/JointPositionController
    joint: joint4
    pid: {p: 1000.0, i: 0.01, d: 0.0}

  joint5_position_controller:
    type: velocity_controllers/JointPositionController
    joint: joint5
    pid: {p: 1000.0, i: 0.01, d: 0.0}

  joint6_position_controller:
    type: velocity_controllers/JointPositionController
    joint: joint6
    pid: {p: 1000.0, i: 0.01, d: 0.0}

## -- Trajectory Controllers --
  joint_trajectory_controller:
    type: "velocity_controllers/JointTrajectoryController"
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    gains:
      joint0: {p: 400.0,i: 0.95, d: 15.0}
      joint1: {p: 2800.0,i: 0.95, d: 18.0}
      joint2: {p: 450.0,i: 1.75, d: 10.0}
      joint3: {p: 1100.0,i: 1.75, d: 12.0}
      joint4: {p: 150.0,i: 5.5, d: 5.0}
      joint5: {p: 120.0,i: 5.5, d: 8.0}
      joint6: {p: 100.0,i: 0.1, d: 0.01}
    contraints:
      joint0:
        goal: 0.1
      joint1:
        goal: 0.1
      joint2:
        goal: 0.1
      joint3:
        goal: 0.1
      joint4:
        goal: 0.1
      joint5:
        goal: 0.1
      joint6:
        goal: 0.1


# ------------ gripper controller config ------------

  left_gripper_position_controller:
    type: velocity_controllers/JointPositionController
    joint: prismatic_finger_left
    pid: {p: 1000.0, i: 0.01, d: 0.0}

  right_gripper_position_controller:
    type: velocity_controllers/JointPositionController
    joint: prismatic_finger_right
    pid: {p: 1000.0, i: 0.01, d: 0.0}


# ------------ mobile base controller config ------------

  diff_drive_controller:
    type        : "diff_drive_controller/DiffDriveController"
    left_wheel  : 'l_wheel_joint'
    right_wheel : 'r_wheel_joint'
    publish_rate: 50.0               # default: 50
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0 # default: 1.0
    wheel_radius_multiplier    : 1.0 # default: 1.0

    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    wheel_separation : 0.36
    wheel_radius : 0.0765

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 1.0

    odom_frame_id: /base_controller/odom

    # Base frame_id
    base_frame_id: base_footprint #default: base_link

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.02  # m/s
        min_velocity           : -1.02 # m/s
        has_acceleration_limits: true
        max_acceleration       : 0.25  # m/s^2
        min_acceleration       : -0.25 # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 6.0  # rad/s
        min_velocity           : -6.0
        has_acceleration_limits: true
        max_acceleration       : 1.5  # rad/s^2
        min_acceleration       : -1.5